// Create sample data structure
export const templateData = [
  {
    studentNumber: "20210010",
    lastName: "Doe",
    firstName: "John",
    middleInit: "A",
    courseCode: "CS101",
    courseTitle: "Introduction to Computer Science",
    creditUnit: 3,
    grade: "1.75",
    reExam: "",
    remarks: "PASSED",
    instructor: "Dr. Smith",
  },
  {
    studentNumber: "20210050",
    lastName: "Smith",
    firstName: "Jane",
    middleInit: "B",
    courseCode: "MATH201",
    courseTitle: "Calculus I",
    creditUnit: 3,
    grade: "2.00",
    reExam: "",
    remarks: "PASSED",
    instructor: "Prof. Johnson",
  },
  {
    studentNumber: "20200090",
    lastName: "Johnson",
    firstName: "Michael",
    middleInit: "C",
    courseCode: "ENG101",
    courseTitle: "English Communication",
    creditUnit: 2,
    grade: "1.50",
    reExam: "",
    remarks: "PASSED",
    instructor: "Ms. Williams",
  },
];
